/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static SentimentAnalysis.subjectivity.*;
import static SentimentAnalysis.sentiment.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import static main.main.*;

public class frmSentimentForPara extends javax.swing.JFrame {

    static DefaultTableModel modelResultsPara;

    /**
     * Creates new form frmSentimentForPara
     */
    public frmSentimentForPara() {
        initComponents();
        modelResultsPara = (DefaultTableModel) tbResultsPara.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpData = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaTestPara = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaCleanPara = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbResultsPara = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSentencePara = new javax.swing.JTextArea();
        cbSubjectivityPara = new javax.swing.JCheckBox();
        cbPassivePara = new javax.swing.JCheckBox();
        cbPositivePara = new javax.swing.JCheckBox();
        cbNegativePara = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbTypeDataPara = new javax.swing.JComboBox();
        btnFilePara = new javax.swing.JButton();
        btnCleanPara = new javax.swing.JButton();
        btnAnalyzePara = new javax.swing.JButton();
        jpResults = new javax.swing.JPanel();
        jpSubjectivity = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbSubPara = new javax.swing.JLabel();
        lbPasPara = new javax.swing.JLabel();
        lbSenSubPara = new javax.swing.JLabel();
        lbPerSubPara = new javax.swing.JLabel();
        lbPerPasPara = new javax.swing.JLabel();
        lbAttSubPara = new javax.swing.JLabel();
        jpSentiment = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbPosPara = new javax.swing.JLabel();
        lbNegPara = new javax.swing.JLabel();
        lbSenSenPara = new javax.swing.JLabel();
        lbPerPosPara = new javax.swing.JLabel();
        lbPerNegPara = new javax.swing.JLabel();
        lbAttSenPara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        txtaTestPara.setColumns(20);
        txtaTestPara.setRows(5);
        jScrollPane1.setViewportView(txtaTestPara);

        jTabbedPane1.addTab("Test", jScrollPane1);

        txtaCleanPara.setColumns(20);
        txtaCleanPara.setRows(5);
        jScrollPane2.setViewportView(txtaCleanPara);

        jTabbedPane1.addTab("Data Cleaned", jScrollPane2);

        tbResultsPara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Sentences", "Subjectivity", "Sentiment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbResultsPara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbResultsParaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbResultsPara);

        jTabbedPane1.addTab("Result", jScrollPane5);

        txtSentencePara.setEditable(false);
        txtSentencePara.setColumns(20);
        txtSentencePara.setLineWrap(true);
        txtSentencePara.setRows(4);
        txtSentencePara.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtSentencePara);

        cbSubjectivityPara.setText("Subjectivity");
        cbSubjectivityPara.setEnabled(false);

        cbPassivePara.setText("Passive");
        cbPassivePara.setEnabled(false);

        cbPositivePara.setText("Positive");
        cbPositivePara.setEnabled(false);

        cbNegativePara.setText("Negative");
        cbNegativePara.setEnabled(false);

        javax.swing.GroupLayout jpDataLayout = new javax.swing.GroupLayout(jpData);
        jpData.setLayout(jpDataLayout);
        jpDataLayout.setHorizontalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jpDataLayout.createSequentialGroup()
                        .addComponent(cbSubjectivityPara)
                        .addGap(18, 18, 18)
                        .addComponent(cbPassivePara)
                        .addGap(18, 18, 18)
                        .addComponent(cbPositivePara)
                        .addGap(18, 18, 18)
                        .addComponent(cbNegativePara)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jpDataLayout.setVerticalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSubjectivityPara)
                    .addComponent(cbPassivePara)
                    .addComponent(cbPositivePara)
                    .addComponent(cbNegativePara))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(java.awt.SystemColor.activeCaption);
        jLabel13.setText("Type:");

        cbTypeDataPara.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Education", "Movie", "Sport" }));
        cbTypeDataPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeDataParaActionPerformed(evt);
            }
        });

        btnFilePara.setText("File");
        btnFilePara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileParaActionPerformed(evt);
            }
        });

        btnCleanPara.setText("Clean");
        btnCleanPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanParaActionPerformed(evt);
            }
        });

        btnAnalyzePara.setText("Analyze");
        btnAnalyzePara.setEnabled(false);
        btnAnalyzePara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeParaActionPerformed(evt);
            }
        });

        jpResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        jpSubjectivity.setBorder(javax.swing.BorderFactory.createTitledBorder("Subjectivity"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaption);
        jLabel2.setText("Subjective:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaption);
        jLabel4.setText("Passive:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaption);
        jLabel3.setText("~");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.activeCaption);
        jLabel5.setText("~");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaption);
        jLabel6.setText("Attention:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("Sentence:");

        lbSubPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSubPara.setForeground(new java.awt.Color(153, 0, 0));
        lbSubPara.setText("0");

        lbPasPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPasPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPasPara.setText("0");

        lbSenSubPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSenSubPara.setForeground(new java.awt.Color(153, 0, 0));
        lbSenSubPara.setText("0");

        lbPerSubPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPerSubPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPerSubPara.setText("0%");

        lbPerPasPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPerPasPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPerPasPara.setText("0%");

        lbAttSubPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAttSubPara.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jpSubjectivityLayout = new javax.swing.GroupLayout(jpSubjectivity);
        jpSubjectivity.setLayout(jpSubjectivityLayout);
        jpSubjectivityLayout.setHorizontalGroup(
            jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSubjectivityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSubjectivityLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAttSubPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpSubjectivityLayout.createSequentialGroup()
                        .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpSubjectivityLayout.createSequentialGroup()
                                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSenSubPara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSubPara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpSubjectivityLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbPasPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPerSubPara, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(lbPerPasPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpSubjectivityLayout.setVerticalGroup(
            jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSubjectivityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbSenSubPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lbSubPara)
                    .addComponent(lbPerSubPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPasPara)
                    .addComponent(lbPerPasPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSubjectivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbAttSubPara))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpSentiment.setBorder(javax.swing.BorderFactory.createTitledBorder("Sentiment"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.activeCaption);
        jLabel8.setText("Positive:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setForeground(java.awt.SystemColor.activeCaption);
        jLabel10.setText("Negative:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.activeCaption);
        jLabel9.setText("~");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setForeground(java.awt.SystemColor.activeCaption);
        jLabel11.setText("~");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(java.awt.SystemColor.activeCaption);
        jLabel12.setText("Attention:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.activeCaption);
        jLabel7.setText("Sentence:");

        lbPosPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPosPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPosPara.setText("0");

        lbNegPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNegPara.setForeground(new java.awt.Color(153, 0, 0));
        lbNegPara.setText("0");

        lbSenSenPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSenSenPara.setForeground(new java.awt.Color(153, 0, 0));
        lbSenSenPara.setText("0");

        lbPerPosPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPerPosPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPerPosPara.setText("0%");

        lbPerNegPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPerNegPara.setForeground(new java.awt.Color(153, 0, 0));
        lbPerNegPara.setText("0%");

        lbAttSenPara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAttSenPara.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jpSentimentLayout = new javax.swing.GroupLayout(jpSentiment);
        jpSentiment.setLayout(jpSentimentLayout);
        jpSentimentLayout.setHorizontalGroup(
            jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSentimentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSentimentLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSenSenPara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpSentimentLayout.createSequentialGroup()
                        .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpSentimentLayout.createSequentialGroup()
                                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPosPara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNegPara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPerPosPara, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(lbPerNegPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lbAttSenPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpSentimentLayout.setVerticalGroup(
            jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSentimentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbSenSenPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbPosPara)
                    .addComponent(jLabel9)
                    .addComponent(lbPerPosPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbNegPara)
                    .addComponent(jLabel11)
                    .addComponent(lbPerNegPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSentimentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbAttSenPara))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpResultsLayout = new javax.swing.GroupLayout(jpResults);
        jpResults.setLayout(jpResultsLayout);
        jpResultsLayout.setHorizontalGroup(
            jpResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSubjectivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpSentiment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpResultsLayout.setVerticalGroup(
            jpResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSubjectivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpSentiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cbTypeDataPara, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFilePara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanPara)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalyzePara)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cbTypeDataPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnalyzePara)
                            .addComponent(btnCleanPara)
                            .addComponent(btnFilePara))
                        .addGap(18, 18, 18)
                        .addComponent(jpResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbResultsParaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResultsParaMouseClicked
        try {
            cbNegativePara.setSelected(false);
            cbPassivePara.setSelected(false);
            cbPositivePara.setSelected(false);
            cbSubjectivityPara.setSelected(false);
            int row = tbResultsPara.getSelectedRow();
            txtSentencePara.setText(tbResultsPara.getModel().getValueAt(row, 1).toString());
            if (tbResultsPara.getModel().getValueAt(row, 2).toString().equalsIgnoreCase("0.0")) {
                cbPassivePara.setSelected(true);
            } else {
                cbSubjectivityPara.setSelected(true);
                if (tbResultsPara.getModel().getValueAt(row, 3).toString().equalsIgnoreCase("0.0")) {
                    cbNegativePara.setSelected(true);
                } else {
                    cbPositivePara.setSelected(true);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbResultsParaMouseClicked

    private void cbTypeDataParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeDataParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeDataParaActionPerformed

    private void btnFileParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileParaActionPerformed
        JFileChooser chooser = new JFileChooser("");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog((java.awt.Component) null);
        if (returnVal == chooser.APPROVE_OPTION) {
            File inFile = chooser.getSelectedFile();
            try {
                FileReader fr = new FileReader(inFile);
                BufferedReader br = new BufferedReader(fr);
                try {
                    txtaTestPara.read(br, null);
                } catch (IOException ex) {
                    Logger.getLogger(frmSentimentAnalysis.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtaTestPara.requestFocus();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmSentimentAnalysis.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFileParaActionPerformed

    private void btnCleanParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanParaActionPerformed
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("data\\dataProcessing\\subjectivity\\sen\\senTemp.txt"))) {
            bw.write(txtaTestPara.getText());
            bw.flush();
        } catch (IOException ex) {
            Logger.getLogger(frmSentimentAnalysis.class.getName()).log(Level.SEVERE, null, ex);
        }
        cleanDataForTrain();
        try {
            FileReader frSubTrain = new FileReader("data\\dataProcessing\\subjectivity\\sen\\sen.txt");
            try (BufferedReader br = new BufferedReader(frSubTrain)) {
                txtaCleanPara.read(br, null);
            }
            txtaCleanPara.requestFocus();
        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnAnalyzePara.setEnabled(true);
    }//GEN-LAST:event_btnCleanParaActionPerformed

    private void btnAnalyzeParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeParaActionPerformed
        int subSen, subSub, subPas, senSen, senPos, senNeg;
        double subPerSub, subPerPas, senPerPos, senPerNeg;
        try {
            if (cbTypeDataPara.getSelectedItem().toString().equalsIgnoreCase("Default")) {
                copyFileForTrain("default");
            }
            if (cbTypeDataPara.getSelectedItem().toString().equalsIgnoreCase("Education")) {
                copyFileForTrain("education");
            }
            if (cbTypeDataPara.getSelectedItem().toString().equalsIgnoreCase("Movie")) {
                copyFileForTrain("movie");
            }
            if (cbTypeDataPara.getSelectedItem().toString().equalsIgnoreCase("Sport")) {
                copyFileForTrain("sport");
            }

            trainSubjectivityIndirectForSentence();
            //trainSubjectivityDirForSentence();
            subSen = readSentence(new File("senOUT.txt"), "data\\dataProcessing\\subjectivity\\sen\\");
            subSub = readResult(new File("outputSub"), "src\\Data\\", "1.0");
            subPerSub = (double) subSub / subSen * 100;
            subPas = subSen - subSub;
            subPerPas = (double) 100 - subPerSub;
            lbSenSubPara.setText(Integer.toString(subSen));
            lbSubPara.setText(Integer.toString(subSub));
            lbPerSubPara.setText((double) Math.round(subPerSub * 10) / 10 + "%");
            lbPasPara.setText(Integer.toString(subPas));
            lbPerPasPara.setText((double) Math.round(subPerPas * 10) / 10 + "%");
            lbAttSubPara.setText(checkAttention(subPerSub));

            exSentimentFileForSentence();
            trainSentimentIndirectForSentence();
            //trainSentimentDirForSentence();
            senSen = readSentence(new File("senOUT.txt"), "data\\dataProcessing\\sentiment\\sen\\");
            senPos = readResult(new File("outputSen"), "src\\Data\\", "1.0");
            senPerPos = (double) senPos / senSen * 100;
            senNeg = senSen - senPos;
            senPerNeg = (double) 100 - senPerPos;
            lbSenSenPara.setText(Integer.toString(senSen));
            lbPosPara.setText(Integer.toString(senPos));
            lbPerPosPara.setText((double) Math.round(senPerPos * 10) / 10 + "%");
            lbNegPara.setText(Integer.toString(senNeg));
            lbPerNegPara.setText((double) Math.round(senPerNeg * 10) / 10 + "%");
            lbAttSenPara.setText(checkAttention(senPerPos));

            showResultsPara();
        } catch (IOException ex) {
            Logger.getLogger(frmSentimentAnalysis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalyzeParaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSentimentForPara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSentimentForPara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSentimentForPara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSentimentForPara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSentimentForPara().setVisible(true);
            }
        });
    }

    //--Hiển thị kết quả
    private void showResultsPara() throws IOException {
        modelResultsPara.setRowCount(0);
        String[][] arr = readResultsPara();
        for (int i = 0; i < arr.length; i++) {
            modelResultsPara.insertRow(modelResultsPara.getRowCount(),
                    new Object[]{Integer.toString(i + 1), arr[i][0], arr[i][1], arr[i][2]});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyzePara;
    private javax.swing.JButton btnCleanPara;
    private javax.swing.JButton btnFilePara;
    private javax.swing.JCheckBox cbNegativePara;
    private javax.swing.JCheckBox cbPassivePara;
    private javax.swing.JCheckBox cbPositivePara;
    private javax.swing.JCheckBox cbSubjectivityPara;
    private javax.swing.JComboBox cbTypeDataPara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpData;
    private javax.swing.JPanel jpResults;
    private javax.swing.JPanel jpSentiment;
    private javax.swing.JPanel jpSubjectivity;
    private javax.swing.JLabel lbAttSenPara;
    private javax.swing.JLabel lbAttSubPara;
    private javax.swing.JLabel lbNegPara;
    private javax.swing.JLabel lbPasPara;
    private javax.swing.JLabel lbPerNegPara;
    private javax.swing.JLabel lbPerPasPara;
    private javax.swing.JLabel lbPerPosPara;
    private javax.swing.JLabel lbPerSubPara;
    private javax.swing.JLabel lbPosPara;
    private javax.swing.JLabel lbSenSenPara;
    private javax.swing.JLabel lbSenSubPara;
    private javax.swing.JLabel lbSubPara;
    private javax.swing.JTable tbResultsPara;
    private javax.swing.JTextArea txtSentencePara;
    private javax.swing.JTextArea txtaCleanPara;
    private javax.swing.JTextArea txtaTestPara;
    // End of variables declaration//GEN-END:variables
}
